language: python
python:
  - "3.6.4"

install:
  - pip install -r requirements.txt

script:
  - pytest

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search